
#ifndef ACOUSEA_MKR1310_NODES_ERRORCODE_H
#define ACOUSEA_MKR1310_NODES_ERRORCODE_H


#include <cstdint>

enum class ErrorCode : uint8_t {
    INVALID_OPCODE = 0x01,
    INVALID_PAYLOAD = 0x02,
    INVALID_SENDER_ADDRESS = 0x03,
    INVALID_RECIPIENT_ADDRESS = 0x04,
    INVALID_PACKET_LENGTH = 0x05,
    INVALID_SYNC_BYTE = 0x06
};
#endif //ACOUSEA_MKR1310_NODES_ERRORCODE_H
